### ISSUE TITLE
The container failed to start and listen on the port defined by the PORT environment variable, but it is actually defined.

### ISSUE THREAD

**Issue by leozinbranco** [adaptable/feathers-template#41]
![image](https://github.com/adaptable/feathers-template/assets/55717308/32043841-19f3-4871-a8fb-faad282e20f3)

Im having this problem, help me i have to use adaptable for my final paper! 

The port is defined. I think the yarn --prefer-ofline are getting the cached modules, or something like this, because it started when i remove one depreceated lib of my code.

**Comment by mterrel** [comment]
Hello, for support for your app on Adaptable.io, please use the support chat icon in the lower right of any page on https://adaptable.io.

Thanks!
